project_id = "qibjqqucmbrtuirysexl"

[functions.create-checkout]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.get-usage]
verify_jwt = false

[functions.increment-usage]
verify_jwt = false